[package]
name = "elevator_sim"
version = "0.1.0"
authors = ["Jörg Bauder <Bauder@aunovis.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
